/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WildlifeWonderlandRouteImport } from './routes/wildlife-wonderland'
import { Route as CenterForTransformativeTechnologyRouteImport } from './routes/center-for-transformative-technology'
import { Route as IndexRouteImport } from './routes/index'

const WildlifeWonderlandRoute = WildlifeWonderlandRouteImport.update({
  id: '/wildlife-wonderland',
  path: '/wildlife-wonderland',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterForTransformativeTechnologyRoute =
  CenterForTransformativeTechnologyRouteImport.update({
    id: '/center-for-transformative-technology',
    path: '/center-for-transformative-technology',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/center-for-transformative-technology': typeof CenterForTransformativeTechnologyRoute
  '/wildlife-wonderland': typeof WildlifeWonderlandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/center-for-transformative-technology': typeof CenterForTransformativeTechnologyRoute
  '/wildlife-wonderland': typeof WildlifeWonderlandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/center-for-transformative-technology': typeof CenterForTransformativeTechnologyRoute
  '/wildlife-wonderland': typeof WildlifeWonderlandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/center-for-transformative-technology'
    | '/wildlife-wonderland'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/center-for-transformative-technology' | '/wildlife-wonderland'
  id:
    | '__root__'
    | '/'
    | '/center-for-transformative-technology'
    | '/wildlife-wonderland'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenterForTransformativeTechnologyRoute: typeof CenterForTransformativeTechnologyRoute
  WildlifeWonderlandRoute: typeof WildlifeWonderlandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wildlife-wonderland': {
      id: '/wildlife-wonderland'
      path: '/wildlife-wonderland'
      fullPath: '/wildlife-wonderland'
      preLoaderRoute: typeof WildlifeWonderlandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center-for-transformative-technology': {
      id: '/center-for-transformative-technology'
      path: '/center-for-transformative-technology'
      fullPath: '/center-for-transformative-technology'
      preLoaderRoute: typeof CenterForTransformativeTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenterForTransformativeTechnologyRoute:
    CenterForTransformativeTechnologyRoute,
  WildlifeWonderlandRoute: WildlifeWonderlandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
